name: Pull Request Build

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.18.0’

      - name: Build application
