name: Pull Request Build

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

      - name: Unit tests
        run: |
          go test -v ./...
