name: Pull Request Build

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

  Unit Test:
    depends-on: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Unit tests
        run: |
          go test -v ./...
