name: Pull Request Build

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.18.0’

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

      - name: Unit tests
        run: |
          go test -v ./...
